version: "3"

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: controlweb_app
    restart: always
    env_file: 
      - ./.env
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$DOCKER_PORT
    ports:
      - $WEB_SERV_PORT:$WEB_SERV_PORT
    volumes:
      - .:/app
    links:
      - database
    depends_on:
      - database
    networks:
      - controlweb_network

  database:
    image: postgres:alpine
    container_name: controlweb_database
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$DOCKER_PORT
    ports:
      - $POSTGRES_PORT:$DOCKER_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - controlweb_network

  # rabbit:
  #   image: "rabbitmq:3-management"
  #   container_name: boleto_rabbitmq
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
  #     RABBITMQ_DEFAULT_USER: "rabbitmq"
  #     RABBITMQ_DEFAULT_PASS: "rabbitmq"
  #     RABBITMQ_DEFAULT_VHOST: "/"
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #   networks:
  #     - controlweb_network

networks:
  controlweb_network:
    driver: bridge

volumes:
  postgres_data: